function init(self)
	msg.post(".", "acquire_input_focus") 
	--print("init input gui?")
end

function on_input(self, action_id, action)
	--print("??")
	if action_id == hash("click") and action.pressed then
		print("click!")
		local button = gui.get_node("button") 
		local text = gui.get_node("text") 
		if gui.pick_node(button, action.x, action.y) then 
			gui.set_text(text, "HELLO!") 
		else
			gui.set_text(text, "CLICK ME!") 
		end
	end
end